apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chaos-demo
  template:
    metadata:
      labels:
        app: chaos-demo
    spec:
      containers:
        - name: chaos-demo
          image: nginx:1.29-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: chaos-demo-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: chaos-demo-html
          configMap:
            name: chaos-demo-html

