apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chaos-go
  template:
    metadata:
      labels:
        app: chaos-go
    spec:
      containers:
      - name: go-chaos
        image: public.ecr.aws/ecs-chrome/edge-chaos:latest  # Replace w/ your ECR
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-service
spec:
  selector:
    app: chaos-go
  ports:
  - port: 80
    targetPort: 8080
