apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-app
  namespace: chaos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chaos-app
  template:
    metadata:
      labels:
        app: chaos-app
    spec:
      containers:
      - name: chaos-app
        image: 089719647189.dkr.ecr.us-east-1.amazonaws.com/chaos-edge-go:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-service
  namespace: chaos
spec:
  selector:
    app: chaos-app
  ports:
  - port: 80
    targetPort: 8080
