---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-app-sa
  namespace: chaos-edge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-app-role
  namespace: chaos-edge
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-app-rolebinding
  namespace: chaos-edge
subjects:
  - kind: ServiceAccount
    name: chaos-app-sa
    namespace: chaos-edge
roleRef:
  kind: Role
  name: chaos-app-role
  apiGroup: rbac.authorization.k8s.io
